#pragma once //header, which stores all header files in program
#include"Libs.h"
#include"Expression.h"
#include"PlusExpressionHeader.h"
#include"BeginWhileExpressionHeader.h"
#include"BiggerExpressionHeader.h"
#include"DotExpression.h"
#include"EndWhileExpressionHeader.h"
#include"MinusExpressionHeader.h"
#include"SmallerExpressionHeader.h"
#include"ParserHeader.h"
#include"Executor.h"
#include"Checker.h"